spring:
  application:
    name: shop-back
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      #ddl-auto: update
    defer-datasource-initialization: true # 데이터 초기화를 위한 설정.
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/shop-backend
    username: root
    password: 1234
  sql:
    init:
      mode: always

payment:
  api:
    base-url: https://junbyoung.free.beeceptor.com
    endpoint: api/v1/payment